name: publish updater

on:
  release:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: deploy updates.json
      - uses: sergeysova/gist-write-action@v1
        with:
          gist_id: d200fcfcadc2220d6885a1a311bcbd3e
          file_name: updates.json
          content: >
            {
              "name": "${{ github.event.release.name }}",
              "notes": "${{ github.event.release.body }}",
              "pub_date": "${{ github.event.release.published_at }}",
              "platforms": {
                "win64": {
                  "signature": "",
                  "url": "${{ github.event.release.assets[0].browser_download_url }}"
                }
              }
            }
