name: publish updater

on:
  release:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: deploy updates.json
        run: |
          echo { \
            "name": "${{ github.event.release.name }}", \
            "notes": "${{ github.event.release.body }}", \
            "pub_date": "${{ github.event.release.published_at }}", \
            "platforms": { \
              "win64": { \
                "signature": "", \
                "url": "${{ github.event.release.assets[0].browser_download_url }}" \
              } \
            } \
          }