name: publish updater

on:
  release:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: update the updates.json
        run: |
          echo { \
            "name": "${{ release.name }}", \
            "notes": "${{ release.body }}", \
            "pub_date": "${{ release.published_at }}", \
            "platforms": { \
              "win64": { \
                "signature": "", \
                "url": "${{ release.assets[0].browser_download_url }}" \
              } \
            } \
          }
